#!/usr/bin/env bash

# Exit if a command exits with a non zero status
set -e

# Install requirements 
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${BASEDIR}/setup/system_requirements.sh

# Configure dotbot - set up all the symlinks
CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"