version: "3.3"
services:
  development:
    build:
      context: .
      dockerfile: $HOME/.dockerfiles/dockerfiles/dev.base.dockerfile
      args:
        - USER
    shm_size: '6gb'
    entrypoint: ["/tini", "-g", "--"]
    command: jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --NotebookApp.token=''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: "development"
    environment:
      - USER=$USER
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/home/$USER/workspace
    ports:
      - 8888:8888
