version: "3.3"
services:
  mission_planner:
    build:
      context: . 
      dockerfile: ../../dockerfiles/drones/mission_planner.dockerfile
    container_name: "mission_planner"
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - dev

  sitl:
    build:
      context: . 
      dockerfile: ../../dockerfiles/drones/sim_vehicle.dockerfile
    container_name: "sim_vehicle"
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["-v", "ArduCopter", "--console", "--map", "--out", "udp:mission_planner:5555"]
    networks:
      - dev

networks:
  dev:
    driver: bridge
